<a href="https://colab.research.google.com/github/tarazevych/HW_for_Python/blob/main/HW8_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [23]:
import pandas as pd
df = pd.read_csv("tip.csv")
display(df.head(5))
display(df.shape)
display(list(df.columns))
display(df.info())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

(244, 7)

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

None

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [18]:
total_bill = df["total_bill"]
display(total_bill)
ttl_bil_tip = df[["total_bill", "tip"]]
display(ttl_bil_tip)
head_10 = df.head(10)
display(head_10)
row_6 = df.loc[5]
display(row_6)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [25]:
ttl_bills_20 = df[df["total_bill"]>20]
print("Всі рахунки більше 20 доларів")
display(ttl_bills_20.shape)
display(ttl_bills_20.head(5))
female = df[df['sex'] == "Female"]
print("Всі відвідувачі-жінки")
display(female.shape)
display(female.head(5))
dinner = df[df["time"] == "Dinner" ]
print("Рахунки на вечерю")
display(dinner.shape)
display(dinner.head(5))
bill_dinner_30 = df[(df["time"] == "Dinner") & (df["total_bill"]>30) ]
print("Рахунки на вечерю з сумою чеку більше 30 доларів")
display(bill_dinner_30.shape)
display(bill_dinner_30.head(5))

Всі рахунки більше 20 доларів

(97, 7)

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

Всі відвідувачі-жінки

(87, 7)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

Рахунки на вечерю

(176, 7)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Рахунки на вечерю з сумою чеку більше 30 доларів

(27, 7)

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [29]:
print("Середній розмір рахунку на всьому наборі даних")
print(df["total_bill"].mean())
print("Максимальні чайові")
print(df["tip"].max())
print("Кількість пропущених значень у всіх колонках")
print(df.isna().sum())
print("Скільки в наборі даних рахунків за обіди і за вечері")
print(df["time"].value_counts())

Середній розмір рахунку на всьому наборі даних
19.78594262295082
Максимальні чайові
10.0
Кількість пропущених значень у всіх колонках
total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64
Скільки в наборі даних рахунків за обіди і за вечері
time
Dinner    176
Lunch      68
Name: count, dtype: int64

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [34]:
print("Середній рахунок за статтю")
print(df.groupby("sex")["total_bill"].mean())
print("Середні чайові за днем тижня")
print(df.groupby("day")["tip"].mean())
print("Скільки відвідувачів у кожен день")
print(df.groupby("day")["total_bill"].count())

Середній рахунок за статтю
sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64
Середні чайові за днем тижня
day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64
Скільки відвідувачів у кожен день
day
Fri     19
Sat     87
Sun     76
Thur    62
Name: total_bill, dtype: int64

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [38]:
df["tip_perc"] = df["tip"] / df["total_bill"] * 100
df.head(10).round(2)

   total_bill   tip     sex smoker  day    time  size  tip_perc
0       16.99  1.01  Female     No  Sun  Dinner     2      5.94
1       10.34  1.66    Male     No  Sun  Dinner     3     16.05
2       21.01  3.50    Male     No  Sun  Dinner     3     16.66
3       23.68  3.31    Male     No  Sun  Dinner     2     13.98
4       24.59  3.61  Female     No  Sun  Dinner     4     14.68
5       25.29  4.71    Male     No  Sun  Dinner     4     18.62
6        8.77  2.00    Male     No  Sun  Dinner     2     22.81
7       26.88  3.12    Male     No  Sun  Dinner     4     11.61
8       15.04  1.96    Male     No  Sun  Dinner     2     13.03
9       14.78  3.23    Male     No  Sun  Dinner     2     21.85

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [40]:
sorted_bill = df.sort_values(by = "total_bill", ascending = True)
print("За розміром рахунку (зростання)")
print(sorted_bill)
sorted_tip = df.sort_values(by = "tip")
print("За чайовими (спадання)")
print(sorted_tip)
top_5 = df.nlargest(5, "tip")
print("топ-5 найбільших чайових ")
print(top_5)

За розміром рахунку (зростання)
     total_bill    tip     sex smoker   day    time  size   tip_perc
67         3.07   1.00  Female    Yes   Sat  Dinner     1  32.573290
92         5.75   1.00  Female    Yes   Fri  Dinner     2  17.391304
111        7.25   1.00  Female     No   Sat  Dinner     1  13.793103
172        7.25   5.15    Male    Yes   Sun  Dinner     2  71.034483
149        7.51   2.00    Male     No  Thur   Lunch     2  26.631158
..          ...    ...     ...    ...   ...     ...   ...        ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3   7.717751
156       48.17   5.00    Male     No   Sun  Dinner     6  10.379905
59        48.27   6.73    Male     No   Sat  Dinner     4  13.942407
212       48.33   9.00    Male     No   Sat  Dinner     4  18.621974
170       50.81  10.00    Male    Yes   Sat  Dinner     3  19.681165

[244 rows x 8 columns]
За чайовими (спадання)
     total_bill    tip     sex smoker   day    time  size   tip_perc
92         5.75   1.00  Female    Yes   Fri  Dinner     2  17.391304
111        7.25   1.00  Female     No   Sat  Dinner     1  13.793103
67         3.07   1.00  Female    Yes   Sat  Dinner     1  32.573290
236       12.60   1.00    Male    Yes   Sat  Dinner     2   7.936508
0         16.99   1.01  Female     No   Sun  Dinner     2   5.944673
..          ...    ...     ...    ...   ...     ...   ...        ...
141       34.30   6.70    Male     No  Thur   Lunch     6  19.533528
59        48.27   6.73    Male     No   Sat  Dinner     4  13.942407
23        39.42   7.58    Male     No   Sat  Dinner     4  19.228818
212       48.33   9.00    Male     No   Sat  Dinner     4  18.621974
170       50.81  10.00    Male    Yes   Sat  Dinner     3  19.681165

[244 rows x 8 columns]
топ-5 найбільших чайових
     total_bill    tip   sex smoker   day    time  size   tip_perc
170       50.81  10.00  Male    Yes   Sat  Dinner     3  19.681165
212       48.33   9.00  Male     No   Sat  Dinner     4  18.621974
23        39.42   7.58  Male     No   Sat  Dinner     4  19.228818
59        48.27   6.73  Male     No   Sat  Dinner     4  13.942407
141       34.30   6.70  Male     No  Thur   Lunch     6  19.533528